version: '3'

services:
  spark:
    build: .
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '4040:4040'
    volumes:
      - ./data:/data
      - ./src:/src
  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    volumes:
      - ./data:/data
      - ./src:/src



#version: '3'
#services:
#  spark:
#    image: bitnami/spark:3.3.1
#    platform: linux/amd64
#    environment:
#      - SPARK_MODE=master
#    ports:
#      - '8888:8888'
#      - '7777:7777'
#    volumes:
#      - ./data:/data
#      - ./src:/src
#  spark-worker:
#    image: bitnami/spark:3.3.1
#    platform: linux/amd64
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark:7777
#      - SPARK_WORKER_MEMORY=4G
#      - SPARK_EXECUTOR_MEMORY=4G
#      - SPARK_WORKER_CORES=4
#    ports:
#      - '8080:8080'
#    volumes:
#      - ./data:/data
#      - ./src:/src