[tool.poetry]
name = "lake_rosa"
version = "3.0.0"
description = "lake abrale"
authors = ["abrale"]
readme = "README.md"
repository = "https://github.com/cervejaria-ambev/pyiris"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
pytest="=7.2.0"
pyspark="3.3.1"